# Generated by Django 5.2.4 on 2025-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="reason",
            field=models.TextField(default="No reason"),
        ),
    ]
