# Generated by Django 5.2.4 on 2025-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpanel", "0002_report_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsupportmessage",
            name="subject",
            field=models.CharField(default="No subject", max_length=255),
        ),
    ]
