# Generated by Django 5.2.4 on 2025-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="city",
            field=models.CharField(default="تهران", max_length=50),
        ),
        migrations.AddField(
            model_name="post",
            name="province",
            field=models.CharField(default="تهران", max_length=50),
        ),
    ]
